spring:
  profiles:
    include: oauth
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://119.198.127.245:3306/blog?useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: doni
    password: 1234

  thymeleaf:
    prefix=classpath: templates/
    suffix: .html
    check-template-location: true
    cache: false
    mvc:
      static-path-pattern: "/static/**"
  devtools:
    restart:
      enabled: true
logging:
  file:
    name: ../log/test.log  # 로깅 파일 위치이다.
  level: # 각 package 별로 로깅 레벨을 지정할 수 있다.
    com.project.study: error
    com.project.study.controller: info
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB